services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - OLLAMA_AVAILABLE_MODELS=${OLLAMA_AVAILABLE_MODELS:-gemma3:4b,gemma4:31b,gemma3:12b}
      - OLLAMA_MAX_TOKENS=${OLLAMA_MAX_TOKENS}
      - OCR_SPACE_API_KEY=${OCR_SPACE_API_KEY}
    volumes:
      - ./docs:/app/docs
      - ./.env:/app/.env